on:
  pull_request:
    types:
      - closed

jobs:
  tflint:
    uses: dnogu/ActionCI/.github/workflows/tflint.yaml@main
    secrets: inherit
  tf-docs:
    uses: dnogu/ActionCI/.github/workflows/tf-docs.yaml@main
    secrets: inherit
